baseURL = 'https://matijakljajic.github.io/'
languageCode = 'en-us'
title = 'matija.'
copyright = 'Matija Kljajić'
buildFuture = false
pluralizeListTitles = false

[menu]
[[menu.main]]
    identifier = "home"
    name = "home"
    pageref = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    pageref = "/about"
    weight = 20

  [[menu.main]]
    identifier = "blog"
    name = "blog"
    pageref = "/blog"
    weight = 30
    
  [[menu.main]]
    identifier = "projects"
    name = "projects"
    pageref = "/projects"
    weight = 40
    
  [[menu.main]]
    identifier = "contact"
    name = "contact"
    pageref = "/contact"
    weight = 50
